services:
  postgres:
    image: postgres:18.0
    container_name: game-postgres
    environment:
      POSTGRES_DB: game
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql
      - ./game.sql:/docker-entrypoint-initdb.d/init.sql
    restart: "no"

  redis:
    image: redis:7-alpine
    container_name: game-redis
    ports:
      - "6379:6379"
    restart: "no"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: game-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: "no"

  nginx:
    image: nginx:alpine
    container_name: game-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/logs:/var/log/nginx
    restart: "no"
    depends_on:
      - postgres
      - redis
      - rabbitmq
